/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import java.util.Random;

import com.player.Player;

public class App {

    public static void main(String[] args) {

    }
}
