/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import java.util.Random;

public class App {

    public static void main(String[] args) {
        Random random = new Random();
        for (int i = 0; i < 20; i++) {
            System.out.println(random.nextInt(6) + 1);
        }
    }
}
